apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: init
spec:
  description: >-
    App Studio Initialize Pipeline Task, include flags for rebuild and auth.
  params:
    - name: image-url
      description: Image URL for testing
    - name: pipeline-run-name
      description: PipelineRun name
    - name: pipeline-run-namespace
      description: PipelineRun namespace  
  results:
    - name: rebuild-if-exists
      description: true if rebuild needs
    - name: exists
      description: true if exists false otherwise 
    - name: registry-auth
      description: docker config location
    - name: git-auth
      description: git for registry.  
  workspaces:
    - name: source
      optional: true
    - name: registry-auth
      optional: true
    - name: git-auth 
      optional: true
  steps:
    - name: appstudio-init  
      image: appstudio-utils
      script: | 
        #!/bin/bash    
        echo "App Studio Build Initialize: $(params.image-url)" 
        echo

        curl --fail -X POST http://pvc-cleaner.$(inputs.params.pipeline-run-namespace).svc:8080/pipeline-run \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -d "pipeline-run-name=$(inputs.params.pipeline-run-name)"

        echo
        echo "Determine if Image Already Exists"
        bash /appstudio-utils/util-scripts/image-exists.sh $(params.image-url) /tekton/results
        
        echo "Rebuild if Image Already Exists set to false."
        # TODO allow external configuration to force rebuilds
        echo -n "false"   /tekton/results/rebuild-if-exists
        echo
