## Sample Pipeline for a Java s2i build provided ootb.
#
## If changed by a user, the App Studio HAS service should push the modified 
## Pipeline definition into the user's repository.


apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    "pipelines.openshift.io/used-by" : "build-cloud"
    "pipelines.openshift.io/runtime" : "java"
    "pipelines.openshift.io/strategy" : "s2i"
  name: java-builder 
spec:
  params:
    - description: 'Source Repository URL'
      name: git-url
      type: string
    - description: 'Revision of the Source Repository'
      name: revision
      type: string
      default: main
    - description: 'Fully Qualified Output Image'
      name: output-image
      type: string
    - description: The path to your source code
      name: path-context 
      type: string
      default: .
    - description: Path to the Dockerfile
      name: dockerfile
      type: string
      default: Dockerfile
  tasks:
    - name: appstudio-init
      params: 
        - name: image-url 
          value: "$(params.output-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: pipeline-run-namespace
          value: "$(context.pipelineRun.namespace)"
      taskRef:
        name: init
      workspaces:
        - name: source
          workspace: workspace  
        - name: registry-auth
          workspace: registry-auth  
        - name: git-auth 
          workspace: git-auth  
    - name: git-clone
      when:
      - input: $(tasks.appstudio-init.results.exists) 
        operator: in
        values: ["false"]
      runAfter:
        - appstudio-init 
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: "$(params.revision)"
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:da1aedf0b17f2b9dd2a46edc93ff1c0582989414b902a28cd79bad8a035c9ea4
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: appstudio-configure-build       
      runAfter:
        - git-clone 
      taskRef:
        name: configure-build
      workspaces:
        - name: source
          workspace: workspace  
        - name: registry-auth
          workspace: registry-auth  
        - name: git-auth 
          workspace: git-auth   
    - name: s2i-java  
      runAfter:
        - appstudio-configure-build
      params:
        - name: VERSION
          value: openjdk-11-ubi8
        - name: PATH_CONTEXT
          value: $(params.path-context)
        - name: TLSVERIFY
          value: 'true'
        - name: MAVEN_CLEAR_REPO
          value: 'false'
        - name: IMAGE
          value: "$(params.output-image)"
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:99cae35f40c7ec050fed3765b2b27e0b8bbea2aa2da7c16408e2ca13c60ff8ee
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: workspace
    - name: show-summary
      runAfter:
        - s2i-java 
      taskRef:
        name: summary
      params:
      - name: pipeline-run-name
        value: "$(context.pipelineRun.name)" 
      - name: git-url
        value: "$(params.git-url)"
      - name: image-url
        value: $(params.output-image)  
    - name: skip-rebuild-summary  
      when:
      - input: $(tasks.appstudio-init.results.exists) 
        operator: in
        values: ["true"]  
      runAfter:
        - appstudio-init
      taskRef:
        name: summary
      params:
      - name: pipeline-run-name
        value: "$(context.pipelineRun.name)" 
      - name: git-url
        value: "$(params.git-url)"
      - name: image-url
        value: $(params.output-image)
  workspaces:
    - name: workspace
    - name: registry-auth
      optional: true
    - name: git-auth 
      optional: true
